{% set name = "sardana" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88b282f8fbaf87dd6182c5654dbd35e06b0a64968c671e3d61bd7171921b88ab

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - {{ pin_subpackage('sardana-server', exact=True) }}
    - {{ pin_subpackage('sardana-client', exact=True) }}

outputs:
  - name: sardana-server
    script: build_core.sh
    build:
      noarch: python
      entry_points:
        - sardana = sardana.cli:main
        - sardanacli = sardana.cli:main
        - MacroServer = sardana.tango.macroserver:main
        - Pool = sardana.tango.pool:main
        - Sardana = sardana.tango:main
        - spock = sardana.spock:main
        - diffractometeralignment = sardana.taurus.qt.qtgui.extra_hkl.diffractometeralignment:main
        - hklscan = sardana.taurus.qt.qtgui.extra_hkl.hklscan:main
        - macroexecutor = sardana.taurus.qt.qtgui.extra_macroexecutor.macroexecutor:main
        - sequencer = sardana.taurus.qt.qtgui.extra_macroexecutor.sequenceeditor:main
        - ubmatrix = sardana.taurus.qt.qtgui.extra_hkl.ubmatrix:main
        - showscan = sardana.taurus.qt.qtgui.extra_sardana.showscanonline:main
    requirements:
      host:
        - pip
        - python >=3.5
      run:
        - click
        - lxml >=2.3
        - pytango >=9.2.5
        - python >=3.5
        - taurus-core >=5.0.0
    test:
      imports:
        - sardana
        - sardana.macroserver
        - sardana.pool
      commands:
        - MacroServer --help
        - Pool --help
        - Sardana --help
        - sardana --help

  - name: sardana-client
    build:
      noarch: python
    requirements:
      host:
        - python >=3.5
      run:
        - {{ pin_subpackage('sardana-server', exact=True) }}
        - taurus-qt >=5.0.0
        - itango >=0.1.6
    test:
      imports:
        - sardana.spock
      commands:
        - pip check
        - sardana --help
        - sardana spock --help
      requires:
        - pip

  - name: sardana-config
    build:
      noarch: python
    requirements:
      host:
        - python >=3.5
      run:
        - {{ pin_subpackage('sardana-server', exact=True) }}
        # itango is needed here otherwise no subcommand can be added to "sardana"
        # as it's part of the requirements
        - itango >=0.1.6
        - dsconfig >=1.6.7
        - pyyaml
        - ruamel.yaml
        - pydantic
        - jsonpatch
    test:
      imports:
        - sardana.config
      commands:
        - sardana config --help

about:
  home: http://www.sardana-controls.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Sardana is a software suite for Supervision, Control and Data Acquisition in scientific installations.
  description: |
    Sardana is a software suite for Supervision,
    Control and Data Acquisition in scientific installations.
    It aims to reduce cost and time of design, development and support of
    the control and data acquisition systems.
    Sardana development was started at the ALBA synchrotron and today is supported
    by a larger community which includes several other laboratories and individuals
    (ALBA, DESY, MaxIV, Solaris, ESRF).
  doc_url: https://sardana-controls.org
  dev_url: https://gitlab.com/sardana-org/sardana

extra:
  recipe-maintainers:
    - beenje
    - cpascual
    - reszelaz
