{% set name = "sardana" %}
{% set version = "3.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acfc428ac9c37b153cc92d9e4ae66e157d5de477cd40a1d3de7d7a3d887f1362

build:
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - {{ pin_subpackage('sardana-core', exact=True) }}
    - {{ pin_subpackage('sardana-qt', exact=True) }}
    - {{ pin_subpackage('sardana-config', exact=True) }}

test:
  commands:
    - pip check
    - sardanactl --help
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: sardana-core
    script: build_core.sh
    build:
      noarch: python
      entry_points:
        - sardanactl = sardana.cli:main
        - MacroServer = sardana.tango.macroserver:main
        - Pool = sardana.tango.pool:main
        - Sardana = sardana.tango:main
        - spock = sardana.spock:main
        - diffractometeralignment = sardana.taurus.qt.qtgui.extra_hkl.diffractometeralignment:main
        - hklscan = sardana.taurus.qt.qtgui.extra_hkl.hklscan:main
        - macroexecutor = sardana.taurus.qt.qtgui.extra_macroexecutor.macroexecutor:_main
        - sequencer = sardana.taurus.qt.qtgui.extra_macroexecutor.sequenceeditor:_main
        - ubmatrix = sardana.taurus.qt.qtgui.extra_hkl.ubmatrix:main
        - showscan = sardana.taurus.qt.qtgui.extra_sardana.showscanonline:_main
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - click
        - itango >=0.1.6
        - ipython <9.0
        - lxml >=2.3
        - pytango >=9.2.5
        - python >={{ python_min }}
        - taurus-core >=5.1.4
    test:
      requires:
        - python {{ python_min }}
      imports:
        - sardana
        - sardana.macroserver
        - sardana.pool
      commands:
        - MacroServer --help
        - Pool --help
        - Sardana --help
        - sardanactl --help

  - name: sardana-qt
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('sardana-core', exact=True) }}
        - taurus-qt >=5.1.4
    test:
      requires:
        - python {{ python_min }}
      imports:
        - sardana.spock
      commands:
        - sardanactl --help
        - sardanactl spock --help

  - name: sardana-config
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('sardana-core', exact=True) }}
        - dsconfig >=1.7.2
        - ruamel.yaml >=0.18.3
        - pydantic <2.0
        - jsonpatch
        - python-graphviz
    test:
      requires:
        - python {{ python_min }}
      imports:
        - sardana.config
      commands:
        - sardanactl config --help

about:
  home: http://www.sardana-controls.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Sardana is a software suite for Supervision, Control and Data Acquisition in scientific installations.
  description: |
    Sardana is a software suite for Supervision,
    Control and Data Acquisition in scientific installations.
    It aims to reduce cost and time of design, development and support of
    the control and data acquisition systems.
    Sardana development was started at the ALBA synchrotron and today is supported
    by a larger community which includes several other laboratories and individuals
    (ALBA, DESY, MaxIV, Solaris, ESRF).
  doc_url: https://sardana-controls.org
  dev_url: https://gitlab.com/sardana-org/sardana

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - cpascual
    - reszelaz
