{% set name = "sardana" %}
{% set version = "3.0.4dev1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sardana-org/sardana/tarball/a6879704b39fc00d3b66828513c50bb49fe56fdf
  fn: sardana-a687970.tar.gz
  sha256: 34d8d4c54dd399b803149357fd92b9707ccd750da5e60e32365d646bbf9dd140

build:
  number: 0
  noarch: python
  entry_points:
    - MacroServer = sardana.tango.macroserver:main
    - Pool = sardana.tango.pool:main
    - Sardana = sardana.tango:main
    - sardanatestsuite = sardana.test.testsuite:main
    - spock = sardana.spock:main
    - diffractometeralignment = sardana.taurus.qt.qtgui.extra_hkl.diffractometeralignment:main
    - hklscan = sardana.taurus.qt.qtgui.extra_hkl.hklscan:main
    - macroexecutor = sardana.taurus.qt.qtgui.extra_macroexecutor.macroexecutor:main
    - sequencer = sardana.taurus.qt.qtgui.extra_macroexecutor.sequenceeditor:main
    - ubmatrix = sardana.taurus.qt.qtgui.extra_hkl.ubmatrix:main
    - showscan = sardana.taurus.qt.qtgui.extra_sardana.showscanonline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - click
    - itango >=0.1.6
    - lxml >=2.3
    - pytango >=9.2.5
    - python >=3.5
    - taurus >=4.7.0

test:
  imports:
    - sardana
    - sardana.macroserver
  commands:
    - pip check
    - MacroServer --help
    - Pool --help
    - Sardana --help
  requires:
    - pip

about:
  home: http://www.sardana-controls.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Sardana is a software suite for Supervision, Control and Data Acquisition in scientific installations.'
  description: |
    Sardana is a software suite for Supervision,
    Control and Data Acquisition in scientific installations.
    It aims to reduce cost and time of design, development and support of
    the control and data acquisition systems.
    Sardana development was started at the ALBA synchrotron and today is supported
    by a larger community which includes several other laboratories and individuals
    (ALBA, DESY, MaxIV, Solaris, ESRF).
  doc_url: https://sardana-controls.org
  dev_url: https://github.com/sardana-org/sardana

extra:
  recipe-maintainers:
    - beenje
    - cpascual
    - reszelaz
