{% set name = "sardana" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4bc59953cb4ab01c9635ec89961e45feccc3006b0e01b584d1374e763e2c29a

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5,<3.12
  run:
    - {{ pin_subpackage('sardana-core', exact=True) }}
    - {{ pin_subpackage('sardana-qt', exact=True) }}
    - {{ pin_subpackage('sardana-config', exact=True) }}

test:
  commands:
    - pip check
    - sardana --help
  requires:
    - pip

outputs:
  - name: sardana-core
    script: build_core.sh
    build:
      noarch: python
      entry_points:
        - sardana = sardana.cli:main
        - sardanacli = sardana.cli:main
        - MacroServer = sardana.tango.macroserver:main
        - Pool = sardana.tango.pool:main
        - Sardana = sardana.tango:main
        - spock = sardana.spock:main
        - diffractometeralignment = sardana.taurus.qt.qtgui.extra_hkl.diffractometeralignment:main
        - hklscan = sardana.taurus.qt.qtgui.extra_hkl.hklscan:main
        - macroexecutor = sardana.taurus.qt.qtgui.extra_macroexecutor.macroexecutor:_main
        - sequencer = sardana.taurus.qt.qtgui.extra_macroexecutor.sequenceeditor:_main
        - ubmatrix = sardana.taurus.qt.qtgui.extra_hkl.ubmatrix:main
        - showscan = sardana.taurus.qt.qtgui.extra_sardana.showscanonline:_main
    requirements:
      host:
        - pip
        - python >=3.5,<3.12
      run:
        - click
        - itango >=0.1.6
        - lxml >=2.3
        - pytango >=9.2.5
        - python >=3.5,<3.12
        - taurus-core >=5.0.0
    test:
      imports:
        - sardana
        - sardana.macroserver
        - sardana.pool
      commands:
        - MacroServer --help
        - Pool --help
        - Sardana --help
        - sardana --help

  - name: sardana-qt
    build:
      noarch: python
    requirements:
      host:
        - python >=3.5,<3.12
      run:
        - {{ pin_subpackage('sardana-core', exact=True) }}
        - taurus-qt >=5.0.0
    test:
      imports:
        - sardana.spock
      commands:
        - sardana --help
        - sardana spock --help

  - name: sardana-config
    build:
      noarch: python
    requirements:
      host:
        - python >=3.5,<3.12
      run:
        - {{ pin_subpackage('sardana-core', exact=True) }}
        - dsconfig >=1.6.7
        - pyyaml
        - ruamel.yaml
        - pydantic <2.0
        - jsonpatch
    test:
      imports:
        - sardana.config
      commands:
        - sardana config --help

about:
  home: http://www.sardana-controls.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Sardana is a software suite for Supervision, Control and Data Acquisition in scientific installations.
  description: |
    Sardana is a software suite for Supervision,
    Control and Data Acquisition in scientific installations.
    It aims to reduce cost and time of design, development and support of
    the control and data acquisition systems.
    Sardana development was started at the ALBA synchrotron and today is supported
    by a larger community which includes several other laboratories and individuals
    (ALBA, DESY, MaxIV, Solaris, ESRF).
  doc_url: https://sardana-controls.org
  dev_url: https://gitlab.com/sardana-org/sardana

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - cpascual
    - reszelaz
