{% set name = "sardana" %}
{% set version = "3.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4015c3db1fcf06fed70b0b2a88d943973856f3ea97685cddde1261911ac92596

build:
  number: 0
  noarch: python
  entry_points:
    - MacroServer = sardana.tango.macroserver:main
    - Pool = sardana.tango.pool:main
    - Sardana = sardana.tango:main
    - sardanatestsuite = sardana.test.testsuite:main
    - spock = sardana.spock:main
    - diffractometeralignment = sardana.taurus.qt.qtgui.extra_hkl.diffractometeralignment:main
    - hklscan = sardana.taurus.qt.qtgui.extra_hkl.hklscan:main
    - macroexecutor = sardana.taurus.qt.qtgui.extra_macroexecutor.macroexecutor:main
    - sequencer = sardana.taurus.qt.qtgui.extra_macroexecutor.sequenceeditor:main
    - ubmatrix = sardana.taurus.qt.qtgui.extra_hkl.ubmatrix:main
    - showscan = sardana.taurus.qt.qtgui.extra_sardana.showscanonline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - click
    - itango >=0.1.6
    - lxml >=2.3
    - pytango >=9.2.5
    - python >=3.5
    - taurus >=5.0.0

test:
  imports:
    - sardana
    - sardana.macroserver
  commands:
    - pip check
    - MacroServer --help
    - Pool --help
    - Sardana --help
  requires:
    - pip

about:
  home: http://www.sardana-controls.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Sardana is a software suite for Supervision, Control and Data Acquisition in scientific installations.
  description: |
    Sardana is a software suite for Supervision,
    Control and Data Acquisition in scientific installations.
    It aims to reduce cost and time of design, development and support of
    the control and data acquisition systems.
    Sardana development was started at the ALBA synchrotron and today is supported
    by a larger community which includes several other laboratories and individuals
    (ALBA, DESY, MaxIV, Solaris, ESRF).
  doc_url: https://sardana-controls.org
  dev_url: https://gitlab.com/sardana-org/sardana

extra:
  recipe-maintainers:
    - beenje
    - cpascual
    - reszelaz
